// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ekdiunwrhaomcqwfkrxj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVrZGl1bndyaGFvbWNxd2ZrcnhqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYyNDAwMDUsImV4cCI6MjA3MTgxNjAwNX0.zAP1xY7qGQZ_VgnAodyImkML_vvBzMy4xWRGlKOUQrw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});